server:
  port: 8182
spring:
  profiles: home
  application:
    name: feature-web
  main:
    allow-bean-definition-overriding: true
  datasource:
    dbgeekplatform:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.99.100:3306/db_geekplatform?characterEncoding=utf8
      username: root
      password: root
mybatis:
  mapper-locations: classpath*:mapper/*/*.xml
#  mybatis.type-aliases-package: cn.forgeeks.service.common.mapper
redis:
  hostName: 192.168.99.100
  port: 6379
  password: ''
  maxActive: ''
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000
  timeout: 5000
