##########################################  个人PC运行环境 #####################################
server:
    port: 8180
spring:
    profiles: home
    application:
        name: order-web
    common:
        host: 127.0.0.1
        username: myuser
        password: mypass
        port: 5672
        publisher-confirms: true
        virtual-host: /
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 4
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:3306/db_geekplatform?characterEncoding=utf8
        username: root
        password: root

elasticsearch:
    host: 127.0.0.1
redis:
    hostName: 192.168.99.100
    port: 32775
    password: ''
    maxActive: ''
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    timeout: 5000









###########################################  公司运行环境 #########################################

---

server:
    port: 8180
spring:
    profiles: work
    application:
        name: order-web
    common:
        host: 192.168.99.100
        username: guest
        password: guest
        port: 32790
        publisher-confirms: true
        virtual-host: /
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 4
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:3306/db_geekplatform?characterEncoding=utf8
        username: root
        password: root

elasticsearch:
    host: 127.0.0.1
redis:
    hostName: 192.168.99.100
    port: 32775
    password: ''
    maxActive: ''
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    timeout: 5000





