##########################################  个人PC运行环境 #####################################

server:
    port: 8180
spring:
    profiles: home
    application:
        name: order-web
    main:
        allow-bean-definition-overriding: true
    rabbit:
        host: 192.168.99.100
        username: admin
        password: admin
        port: 5672
        publisher-confirms: true
        publisher-returns: true
        virtual-host: my_vhost
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 4
    datasource:
        dbgeekplatform:
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://192.168.99.100:3306/db_geekplatform?characterEncoding=utf8
            username: root
            password: root
        dblog:
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://192.168.99.100:3306/db_geek_log?characterEncoding=utf8
            username: root
            password: root
    kafka:
        bootstrap-servers: 192.168.99.100:9092
        consumer:
            auto-commit-interval: 100
            auto-offset-reset: earliest
            enable-auto-commit: true
            group-id: test-consumer-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
        producer:
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            retries: 0
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis:
    mapper-locations: classpath*:mapper/*/*.xml
    mybatis.type-aliases-package: cn.forgeeks.awesome.order.mapper


elasticsearch:
    host: 192.168.99.100
    port: 9200

redis:
    hostName: 192.168.99.100
    port: 6379
    password: ''
    maxActive: ''
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    timeout: 5000

fdfs:
    soTimeout: 1500
    connectTimeout: 600
    thumbImage:             #缩略图生成参数
        width: 150
        height: 150
    trackerList:            #TrackerList参数,支持多个
        - 192.168.99.100:22122

queue:
    noconsumer:
        status: no
###########################################  公司运行环境 #########################################

---


server:
    port: 8181
spring:
    profiles: work
    application:
        name: order-web
    main:
        allow-bean-definition-overriding: true
    rabbit:
        host: 192.168.99.100
        username: admin
        password: admin
        port: 5672
        publisher-confirms: true
        virtual-host: my_vhost
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 10
    datasource:
        dbgeekplatform:
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://192.168.99.100:3306/db_geekplatform?characterEncoding=utf8
            username: root
            password: root
        dblog:
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://192.168.99.100:3306/db_geek_log?characterEncoding=utf8
            username: root
            password: root
    kafka:
        bootstrap-servers: 192.168.99.100:9092
        consumer:
            auto-commit-interval: 100
            auto-offset-reset: earliest
            enable-auto-commit: true
            group-id: test-consumer-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
        producer:
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            retries: 0
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis:
    mapper-locations: classpath*:mapper/*/*.xml
    mybatis.type-aliases-package: cn.forgeeks.awesome.order.mapper


elasticsearch:
    host: 192.168.99.100
    port: 9200

redis:
    hostName: 192.168.99.100
    port: 6379
    password: ''
    maxActive: ''
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    timeout: 5000

fdfs:
    soTimeout: 1500
    connectTimeout: 600
    thumbImage:             #缩略图生成参数
        width: 150
        height: 150
    trackerList:            #TrackerList参数,支持多个
        - 192.168.99.100:22122


